delete from TELEFONO where TELEFONO.IDUSUARIO=6;
delete from MAIL where MAIL.IDUSUARIO=6;
delete from TITULO where TITULO.IDUSUARIOPERSONAL=6;
delete from PERSONAL WHERE PERSONAL.IDUSUARIO=6;
delete from USUARIO WHERE USUARIO.IDUSUARIO=6;
