'use strict';

angular.module('clientAppApp')
.constant('todosLosTrimData', 


{ 
  "ano": "4º",
  "division": "U",
  "anoEscolar": 2016,
  "listaTrimestres" :[
  {
    "alumno" : "Martin Herrlein",
    "primerTrim": 6,
    "segundoTrim": 9,
    "tercerTrim": 8,
    "califAnual": 7,
    "califDic": null,
    "califMarzo": null,
  },
  {
    "alumno" : "Eric Pennachini",
    "primerTrim": 6,
    "segundoTrim": 8,
    "tercerTrim": 4,
    "califAnual": 5,
    "califDic": 6,
    "califMarzo": null,
  },
  {
    "alumno" : "Daniel Pacheco",
    "primerTrim": 6,
    "segundoTrim": 9,
    "tercerTrim": 5,
    "califAnual": 5,
    "califDic": 5,
    "califMarzo": 5,
  },
  {
    "alumno" : "Ariel Ramirez",
   "primerTrim": 6,
    "segundoTrim": 9,
    "tercerTrim": 8,
    "califAnual": 7,
    "califDic": null,
    "califMarzo": null,
  },
  {
    "alumno" : "Martin Herrlein",
    "primerTrim": 6,
    "segundoTrim": 9,
    "tercerTrim": 8,
    "califAnual": 7,
    "califDic": null,
    "califMarzo": null,
  },
  {
    "alumno" : "Eric Pennachini",
    "primerTrim": 6,
    "segundoTrim": 9,
    "tercerTrim": 5,
    "califAnual": 5,
    "califDic": 5,
    "califMarzo": 5,
  },
  {
    "alumno" : "Daniel Pacheco",
    "primerTrim": 6,
    "segundoTrim": 9,
    "tercerTrim": 8,
    "califAnual": 7,
    "califDic": null,
    "califMarzo": null,
  },
  {
    "alumno" : "Ariel Ramirez",
    "primerTrim": 6,
    "segundoTrim": 9,
    "tercerTrim": 5,
    "califAnual": 5,
    "califDic": 5,
    "califMarzo": 5,
  },
  {
    "alumno" : "Martin Herrlein",
    "primerTrim": 7,
    "segundoTrim": 7,
    "tercerTrim": 7,
    "califAnual": 7,
    "califDic": null,
    "califMarzo": null,
  },
  {
    "alumno" : "Eric Pennachini",
    "primerTrim": 9,
    "segundoTrim": 10,
    "tercerTrim": 10,
    "califAnual": 9,
    "califDic": null,
    "califMarzo": null,
  },
  {
    "alumno" : "Daniel Pacheco",
    "primerTrim": 6,
    "segundoTrim": 9,
    "tercerTrim": 8,
    "califAnual": 7,
    "califDic": null,
    "califMarzo": null,
  },
  {
    "alumno" : "Ariel Ramirez",
    "primerTrim": 4,
    "segundoTrim": 4,
    "tercerTrim": 8,
    "califAnual": 5,
    "califDic": 5,
    "califMarzo": 9,
  },
  {
    "alumno" : "Martin Herrlein",
    "primerTrim": 6,
    "segundoTrim": 9,
    "tercerTrim": 8,
    "califAnual": 7,
    "califDic": null,
    "califMarzo": null,
  },
  {
    "alumno" : "Eric Pennachini",
    "primerTrim": 4,
    "segundoTrim": 4,
    "tercerTrim": 8,
    "califAnual": 5,
    "califDic": 5,
    "califMarzo": 9,
  },
  {
    "alumno" : "Daniel Pacheco",
    "primerTrim": 6,
    "segundoTrim": 9,
    "tercerTrim": 8,
    "califAnual": 7,
    "califDic": null,
    "califMarzo": null,
  },
  {
    "alumno" : "Ariel Ramirez",
    "primerTrim": 6,
    "segundoTrim": 9,
    "tercerTrim": 8,
    "califAnual": 7,
    "califDic": null,
    "califMarzo": null,
  },
  {
    "alumno" : "Martin Herrlein",
    "primerTrim": 1,
    "segundoTrim": 2,
    "tercerTrim": 6,
    "califAnual": 4,
    "califDic": 4,
    "califMarzo": null,
  },
  {
    "alumno" : "Eric Pennachini",
    "primerTrim": 4,
    "segundoTrim": 4,
    "tercerTrim": 8,
    "califAnual": 5,
    "califDic": 5,
    "califMarzo": 9,
  },
  {
    "alumno" : "Daniel Pacheco",
    "primerTrim": 6,
    "segundoTrim": 9,
    "tercerTrim": 8,
    "califAnual": 7,
    "califDic": null,
    "califMarzo": null,
  },
  {
    "alumno" : "Ariel Ramirez",
    "primerTrim": 1,
    "segundoTrim": 2,
    "tercerTrim": 6,
    "califAnual": 4,
    "califDic": 4,
    "califMarzo": null,
  },
  {
    "alumno" : "Martin Herrlein",
    "primerTrim": 6,
    "segundoTrim": 9,
    "tercerTrim": 8,
    "califAnual": 7,
    "califDic": null,
    "califMarzo": null,
  },
  {
    "alumno" : "Eric Pennachini",
    "primerTrim": 1,
    "segundoTrim": 2,
    "tercerTrim": 6,
    "califAnual": 4,
    "califDic": 4,
    "califMarzo": null,
  },
  {
    "alumno" : "Daniel Pacheco",
    "primerTrim": 6,
    "segundoTrim": 9,
    "tercerTrim": 8,
    "califAnual": 7,
    "califDic": null,
    "califMarzo": null,
  },
  {
    "alumno" : "Ariel Ramirez",
    "primerTrim": 10,
    "segundoTrim": 8,
    "tercerTrim": 8,
    "califAnual": 9,
    "califDic": null,
    "califMarzo": null,
  }

  ]
});
